# Generated by Django 4.2.5 on 2023-09-10 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentrequest',
            old_name='request_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='uuid',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='request_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
