# Generated by Django 4.2.5 on 2023-09-10 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0002_rename_request_date_documentrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='document',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='request_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
