# Generated by Django 4.2.5 on 2023-09-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0003_remove_documentrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='link_used',
            field=models.BooleanField(default=False),
        ),
    ]
