# Generated by Django 4.2.5 on 2023-09-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0005_documentrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='uploaded_at',
        ),
    ]
