# Generated by Django 4.2.5 on 2023-09-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0006_remove_documentrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
