# Generated by Django 4.2.5 on 2023-09-11 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0007_client_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='request_uuid',
            field=models.UUIDField(default=uuid.UUID, unique=True),
        ),
    ]
