# Generated by Django 4.2.5 on 2023-09-11 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('document_requests', '0008_alter_documentrequest_request_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='request_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
